### PR TITLE
Brings apps back to fragments

### PR DESCRIPTION
**Pull request by sigrunixia**
- Temporary breaks Publish generation
- Fixes Cyan dark mode problem

This will not close the refactor issue but is needed first

### CODE REVIEW

**Comment by ebullient** [comment]
ok. cyan fix I get. ;)

for the rest, we're just re-simplifying the separation of app?

**Comment by sigrunixia** [comment]
Yeah, we’re gonna fully separate out Publish so I can build it lightweight. Once you say my re-combination is fine, I will then work on rebuilding the Publish files. It’ll be in the same PR but want to do this step by step so it’s not overwhelming for you.On Oct 12, 2024, at 08:32, Erin Schnabel ***@***.***> wrote:﻿
ok. cyan fix I get. ;)
for the rest, we're just re-simplifying the separation of app?

**Review by ebullient — APPROVED** [review]

**Comment by ebullient** [comment]
Should we merge this and make a next one? (it won't create an update until I push a release.. )

**Comment by sigrunixia** [comment]
Oh sure! Do go ahead since it met your approval.

**Pull request merged**
